#!/bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus       true

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/bin/polybar.sh

if [ -f "$XDG_CONFIG_HOME/bspwm/autostart" ]; then
  . "$XDG_CONFIG_HOME/bspwm/autostart"
fi

