#!/bin/sh

sxhkd &

# Monitors
i=0
n=`bspc query -M | wc -l`  # count number of lines in bspwm's monitor list
per=$(( 8 / n ))          # number of desktops per monitor
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))` 
    # seq is end-inclusive; `seq 1 $((1+2))` returns "1 2 3"
    i=$(( i + per ))
done

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config click_to_focus       true

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2

$HOME/bin/polybar.sh

# source local configuration
if [ -f "$XDG_CONFIG_HOME/bspwm/bspwmrc_local" ]; then
  . "$XDG_CONFIG_HOME/bspwm/bspwmrc_local"
fi

# Autostart
if [ -f "$XDG_CONFIG_HOME/bspwm/autostart" ]; then
  . "$XDG_CONFIG_HOME/bspwm/autostart"
fi

